apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: btn-brukermelding-producer
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://btn-brukermelding-producer.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics